### PR TITLE
Add GitHub actions & Prettier

### PR DESCRIPTION
**Pull request by shitiomatic**

### CODE REVIEW

**Comment by shitiomatic** [comment]
- Auto publish to gh-pages branch
- Add prettier for all markdown file

**Comment by kelimuttu** [comment]
@shitiomatic Sorry, there was an apocalypse and I decided to revert it back to https://github.com/kelimuttu/kartiniteknologi/commit/e6b37f11a7045aabcc647ba74d1f1bdf8e319479

Would you mind to send another PR once I'm done with https://github.com/kelimuttu/kartiniteknologi/issues/29 ?

**Comment by shitiomatic** [comment]
Sure, :smile: commit history is pretty messy

**Comment by kelimuttu** [comment]
I know.. It's been awhile since I code and this github actions thing is something new to me. 

It seems that the code is still there, and the deployment was successful https://github.com/kelimuttu/kartiniteknologi/actions/runs/192389407. But the site doesn't seem to appear. Can you help? No rush, though.

**Comment by bejoistic** [comment]
Just create empty gh-pages branch, then github actions will auto build and upload to your gh-pages branch. Don't merge from gh-pages to master.

**Comment by kelimuttu** [comment]
Fixed by changing Github page to point to gh-pages branch. Thanks for the help!

**Comment by bejoistic** [comment]
Mantapp

**Pull request merged**
